export enum FreePrefixes {
    rect = "Rectangle",
    txt = "Text Input",
    lbl = "Text Label",
    btn = "Button",
    img_svg = "Image",
    html = "HTML Text",
    ci = "Circle",
    tr = "Triangle",
    st = "5-point, 6-point 8-point, 12-point Star",
    oc = "Octagon",
    pe = "Pentagon",
    combo = "Combo Box",
    dropdown = "Drop Down",
    check = "Check Box",
    list = "List Box",
    radio = "Radio",
    toggle = "Toggle",
    picker = "Date Picker",
    richtxt = "Rich Text Editor",
    sl = "Slider",
    ti = "Timer",
    gall = "Vertical Gallery",
    cont = "Manual Layout Container",
    form = "Edit Form",
    cal = "Calendar component created in Power Apps",
}